version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      time: "14:00"
      timezone: Europe/Paris

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "18:00"
      timezone: Europe/Paris
