extends: default

rules:
  line-length:
    max: 120
    level: warning
  # Everything below is added to match ansible-lint rules
  # see https://ansible.readthedocs.io/projects/lint/rules/yaml/#yamllint-configuration
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-start: disable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
