version: "3"

services:
  database:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=geotribu
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=geotripad
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      backend:
    restart: always

  app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:1.9.4-alpine
    environment:
      - CMD_DB_URL=postgres://hedgedoc:geotribu@database:5432/geotripad
      - CMD_DOMAIN=localhost
      - CMD_URL_ADDPORT=true
    volumes:
      - uploads:/hedgedoc/public/uploads
    ports:
      - "3000:3000"
    networks:
      backend:
    restart: always
    depends_on:
      - database

# Define networks to allow best isolation
networks:
  # Internal network for communication with PostgreSQL
  backend:

volumes:
  database:
  uploads:
