---
# env
test: true
vagrant: true

# network
http_port: 80
https_port: 443

# www-data
hostname: geotribu.local
geotribu_www: geotribu
georezo_www: georezo

# misc
scripts_folder: "/home/geotribu/scripts/"

# cdn
cdn_subdomain: cdn
cdn_path: "/var/www/geotribu/cdn/"

# certificats
georezo_cert_mail: elpaso@georezo.net
geotribu_cert_mail: facteur@geotribu.fr

# comments
comments_subdomain: comments

# pad
pad_user_name: geotripad
pad_pguser: geotripad
pad_pgpass: geotripad
pad_db: pad
