---
# Paquets logiciels
- name: Ajoute le dépôt de Git
  ansible.builtin.apt_repository:
    repo: "ppa:git-core/ppa"
  become: true

- name: "Installe les paquets de base"
  ansible.builtin.apt:
    name:
      - acl # évite les erreurs https://docs.ansible.com/ansible/latest/user_guide/become.html#resolving-temporary-file-error-messsages
      - fail2ban
      - ntp
      - curl
      - apt-transport-https
      - git
      - lsb-release
      - python3-pip
      - python3-setuptools
      - ufw
    update_cache: true
    state: present
  become: true

- name: MAJ les paquets installés
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 86400 # 1 jour

- name: Nettoie les paquets inutilisés
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: "Met à jour pip"
  ansible.builtin.pip:
    name: pip
    executable: pip3

# Utilisateurs et groupes
- name: "S'assure que le groupe 'geoadmins' existe"
  become: true
  ansible.builtin.group:
    name: geoadmins
    state: present

- name: "S'assure que le groupe 'geocontributors' existe"
  become: true
  ansible.builtin.group:
    name: geocontributors
    state: present

- name: "Ajoute l'utilisateur 'geotribu' with a bash shell, appending the group 'admins' and 'contributors' and 'www-data' to the user's groups"
  become: true
  ansible.builtin.user:
    append: true
    createhome: true
    name: geotribu
    shell: /bin/bash
    groups: geoadmins, geocontributors, sudo, www-data

# Pare-feu
- name: Pare-feu UFW - Autorise SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Pare-feu UFW - Autorise HTTP sur le port {{ http_port }}
  become: true
  community.general.ufw:
    comment: rule set by Geotribu Ansible playbook
    rule: allow
    port: "{{ http_port }}"
    proto: tcp
    state: enabled

- name: Pare-feu UFW - Autorise HTTPS sur le port {{ https_port }}
  become: true
  community.general.ufw:
    comment: rule set by Geotribu Ansible playbook
    rule: allow
    port: "{{ https_port }}"
    proto: tcp
    state: enabled

# Divers
- name: Copie les fichiers de profil
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "$HOME"
    owner: geotribu
    backup: true
    mode: preserve
  with_fileglob:
    - files/.*
  become_user: geotribu
  become: true
