---
# Paquets logiciels
- name: Ajoute le dépôt de Git
  ansible.builtin.apt_repository:
    repo: "ppa:git-core/ppa"
  become: true

- name: "Installe les paquets de base"
  ansible.builtin.apt:
    name:
      - acl # évite les erreurs https://docs.ansible.com/ansible/latest/user_guide/become.html#resolving-temporary-file-error-messsages
      - curl
      - fail2ban
      - fzf
      - git
      - lsb-release
      - pipx
      - python3-pip
      - python3-setuptools
      - ufw
    update_cache: true
    state: present
  become: true

- name: MAJ les paquets installés
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: 86400 # 1 jour

- name: Nettoie les paquets inutilisés
  become: true
  ansible.builtin.apt:
    autoremove: true

# Utilisateurs et groupes
- name: "S'assure que le groupe 'geoadmins' existe"
  become: true
  ansible.builtin.group:
    name: geoadmins
    state: present

- name: "S'assure que le groupe 'geocontributors' existe"
  become: true
  ansible.builtin.group:
    name: geocontributors
    state: present

- name: "Ajoute l'utilisateur 'geotribu' with a bash shell, appending the group 'admins' and 'contributors' and 'www-data' to the user's groups"
  become: true
  ansible.builtin.user:
    append: true
    createhome: true
    groups: geoadmins, geocontributors, sudo, www-data
    name: geotribu
    shell: /bin/bash
    state: present

- name: Ajoute la clé SSH à geotribu
  ansible.posix.authorized_key:
    user: geotribu
    state: present
    key: "{{ lookup('file', item) }}"
  become: true
  loop:
    - files/ssh_id_gounux.pub
    - files/ssh_id_guts.pub

- name: Définir un mot de passe à l'utilisateur geotribu si playbook lancé avec Vagrant
  ansible.builtin.user:
    name: geotribu
    password: "{{ 'geotribu' | password_hash('sha512') }}"
    update_password: on_create
  when: geotribu_set_password | default(false)
  become: true

# Pare-feu
- name: Pare-feu UFW - Autorise SSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Pare-feu UFW - Autorise HTTP sur le port {{ http_port }}
  become: true
  community.general.ufw:
    comment: rule set by Geotribu Ansible playbook
    rule: allow
    port: "{{ http_port }}"
    proto: tcp
    state: enabled

- name: Pare-feu UFW - Autorise HTTPS sur le port {{ https_port }}
  become: true
  community.general.ufw:
    comment: rule set by Geotribu Ansible playbook
    rule: allow
    port: "{{ https_port }}"
    proto: tcp
    state: enabled

- name: Pare-feu UFW - S'assurer qu'il est activé
  become: true
  community.general.ufw:
    state: enabled

# Divers
- name: Copie les fichiers de profil
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/geotribu/"
    backup: true
    mode: preserve # copy has a special mode that sets the same permissions as the source file
    owner: geotribu
  with_fileglob:
    - files/.*
  become: true # <- Activates privilege escalation.
  become_user: geotribu
