---
- name: Ajoute le dépôt PPA à jour pour PHP
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"

- name: Ajoute le dépôt PPA à jour pour Apache
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/apache2"

- name: Installation des paquets liés à Apache
  become: true
  ansible.builtin.apt:
    name:
      - apache2
      - brotli
    state: present
    update_cache: true

- name: Installation des paquets liés à PHP
  become: true
  ansible.builtin.apt:
    name:
      - php8.1
      - php8.1-common
      - php8.1-fileinfo
      - php8.1-fpm
      - php8.1-iconv
      - php8.1-mbstring
      - php8.1-zip
    state: present
    update_cache: true

# Apache modules
- name: Désactive les modules Apache
  become: true
  community.general.apache2_module:
    name: "{{ item }}"
    state: absent
    ignore_configcheck: true
  loop:
    - mpm_prefork
    - mpm_worker

- name: Active les modules Apache
  become: true
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
    # ignore_configcheck: true
  loop:
    - brotli
    - headers
    - http2
    - mpm_event
    - proxy_fcgi
    - setenvif

- name: Active la configuration pour php8 FPM
  become: true
  ansible.builtin.command: >
    a2enconf php8.1-fpm
  args:
    creates: "/etc/apache2/conf-enabled/php8.1-fpm.conf"
  when: item.state is not defined or item.state != 'absent'
  notify: Restart Apache
  changed_when: true

# Installe TinyFileManager
- name: Crée le dossier de destination
  become: true
  ansible.builtin.file:
    path: "/var/www/{{ geotribu_www }}/{{ cdn_subdomain }}/images/"
    state: directory
    mode: "0755"

- name: Copie les fichiers de TinyFileManager
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/www/{{ geotribu_www }}/{{ cdn_subdomain }}/"
    owner: geotribu
    group: www-data
    mode: "0770"
    backup: true
  with_fileglob:
    - "files/config.php"
    - "files/tinyfilemanager.php"
    - "files/translation.json"

- name: Copie la configuration Apache2 du CDN
  become: true
  ansible.builtin.template:
    src: "templates/apache_cdn.conf.j2"
    dest: "/etc/apache2/sites-available/{{ geotribu_www }}-{{ cdn_subdomain }}.conf"
    mode: preserve

- name: Active le site
  become: true
  ansible.builtin.command: "/usr/sbin/a2ensite {{ geotribu_www }}-{{ cdn_subdomain }}"
  # notify: Restart Apache
  changed_when: true

- name: Désactive le site par défaut d'Apache
  become: true
  ansible.builtin.command: "/usr/sbin/a2dissite 000-default.conf"
  notify: Restart Apache
  changed_when: true

- name: Crée un certificat SSL pour {{ cdn_subdomain }}
  ansible.builtin.command: >-
    certbot --apache
    --noninteractive
    -d {{ cdn_subdomain }}.{{ hostname }}
    --email {{ geotribu_cert_mail }}
    --agree-tos
  become: true
  register: cert_created
  notify: Reload Apache
  changed_when: true
