---
# if all tasks are successfull
- name: Reload Apache CDN
  ansible.builtin.service:
    name: apache2
    state: reloaded
  become: true
  tags:
    - cdn
    - geotribu

- name: Restart Apache CDN
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true
  tags:
    - cdn
    - geotribu
