- name: restart postgresql
  service:
    name: "postgresql@{{ postgres_version }}-main"
    state: restarted

- name: reload postgresql
  service:
    name: "postgresql@{{ postgres_version }}-main"
    state: reloaded
