- name: Restart postgresql
  ansible.builtin.service:
    name: "postgresql@{{ postgres_version }}-main"
    state: restarted

- name: Reload postgresql
  ansible.builtin.service:
    name: "postgresql@{{ postgres_version }}-main"
    state: reloaded
