---
# Installation de Docker
# Voir : https://docs.docker.com/engine/install/ubuntu/
- name: Désinstalle les anciennes version de Docker
  ansible.builtin.package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: true

- name: "Installe les paquets de base"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true
    state: present
  become: true

- name: "Ajoute le dépôt de Docker"
  ansible.builtin.deb822_repository:
    name: "docker-{{ ansible_distribution_release }}"
    types: deb
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    architectures: amd64
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  become: true

- name: Installe les différents composants de Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

- name: Crée le groupe Docker
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: "Ajoute l'utilisateur geotribu au groupe Docker"
  ansible.builtin.user:
    name: geotribu
    groups: docker
    state: present
    append: true
  become: true

- name: "Ajoute l'utilisateur geotripad au groupe Docker"
  ansible.builtin.user:
    name: "{{ pad_user_name }}"
    groups: docker
    state: present
    append: true
  become: true

- name: Planifie un nettoyage mensuel des objets Docker inutilisés
  ansible.builtin.cron:
    name: "Nettoyage des objets inutilisés de Docker"
    user: geotribu
    job: "docker system prune --volumes --force --all"
    special_time: monthly
  become_user: geotribu
  become: true
