georezo:
  hosts:
    geotribu_prod:
      ansible_host: geotribu
      ansible_user: ubuntu

    geotributest:
      ansible_host: geotribu.local
      ansible_user: geotribu
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
