---
# Source: https://github.com/geerlingguy/ansible-role-certbot/blob/master/tasks/install-with-snap.yml
- name: Vérifie que snapd est installé
  ansible.builtin.package:
    name: snapd
    state: present
  register: snapd_install

- name: Vérifie que snapd est activé
  ansible.builtin.systemd:
    name: snapd.socket
    enabled: true
    state: started

- name: Active le support du confinement classique
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  when: ansible_os_family != "Debian"

- name: MAJ snap
  ansible.builtin.command: snap install core; snap refresh core
  changed_when: true
  failed_when: false
  when: snapd_install is changed # noqa: no-handler

- name: Installe le snap certbot
  community.general.snap:
    name: certbot
    classic: true

- name: Lien symbolique vers le snap certbot
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Expose le script certbot comme variable Ansible
  ansible.builtin.set_fact:
    certbot_script: /usr/bin/certbot
